# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 1) do

  create_table "sayings", :force => true do |t|
    t.column "person_name", :string, :default => "", :null => false
    t.column "sentence",    :text,   :default => "", :null => false
  end

end
